//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18033
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JeffWilcox.FourthAndMayor.UI.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JeffWilcox.FourthAndMayor.UI.Resources.AppResources", typeof(AppResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to add.
        /// </summary>
        public static string AppBarButtonText {
            get {
                return ResourceManager.GetString("AppBarButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu Item.
        /// </summary>
        public static string AppBarMenuItemText {
            get {
                return ResourceManager.GetString("AppBarMenuItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4ᵀᴴ &amp; MAYOR.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foursquare House Rules.
        /// </summary>
        public static string FoursquareHouseRules {
            get {
                return ResourceManager.GetString("FoursquareHouseRules", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foursquare Terms.
        /// </summary>
        public static string FoursquareTerms {
            get {
                return ResourceManager.GetString("FoursquareTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Friends in other cities.
        /// </summary>
        public static string GroupFriendsInOtherCities {
            get {
                return ResourceManager.GetString("GroupFriendsInOtherCities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last 3 Hours.
        /// </summary>
        public static string GroupLast3Hours {
            get {
                return ResourceManager.GetString("GroupLast3Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Older.
        /// </summary>
        public static string GroupOlder {
            get {
                return ResourceManager.GetString("GroupOlder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Today.
        /// </summary>
        public static string GroupToday {
            get {
                return ResourceManager.GetString("GroupToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yesterday.
        /// </summary>
        public static string GroupYesterday {
            get {
                return ResourceManager.GetString("GroupYesterday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s early in the morning!.
        /// </summary>
        public static string InformalEarlyMorning {
            get {
                return ResourceManager.GetString("InformalEarlyMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good afternoon..
        /// </summary>
        public static string InformalGoodAfternoon {
            get {
                return ResourceManager.GetString("InformalGoodAfternoon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good evening..
        /// </summary>
        public static string InformalGoodEvening {
            get {
                return ResourceManager.GetString("InformalGoodEvening", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Good morning..
        /// </summary>
        public static string InformalGoodMorning {
            get {
                return ResourceManager.GetString("InformalGoodMorning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Having a good night?.
        /// </summary>
        public static string InformalGoodNight {
            get {
                return ResourceManager.GetString("InformalGoodNight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Greetings..
        /// </summary>
        public static string InformalGreetings {
            get {
                return ResourceManager.GetString("InformalGreetings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello..
        /// </summary>
        public static string InformalHello {
            get {
                return ResourceManager.GetString("InformalHello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hey..
        /// </summary>
        public static string InformalHey {
            get {
                return ResourceManager.GetString("InformalHey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi..
        /// </summary>
        public static string InformalHi {
            get {
                return ResourceManager.GetString("InformalHi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading.
        /// </summary>
        public static string InformalLoading {
            get {
                return ResourceManager.GetString("InformalLoading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lunchtime!.
        /// </summary>
        public static string InformalLunchtime {
            get {
                return ResourceManager.GetString("InformalLunchtime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location is turned off.
        /// </summary>
        public static string LocationOffTitle {
            get {
                return ResourceManager.GetString("LocationOffTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your location is currently turned off. Change your settings through the Settings charm to turn it back on..
        /// </summary>
        public static string LocationOffUseCharms {
            get {
                return ResourceManager.GetString("LocationOffUseCharms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Location Service.
        /// </summary>
        public static string LocationService {
            get {
                return ResourceManager.GetString("LocationService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tour 4th &amp; Mayor.
        /// </summary>
        public static string OobeTour {
            get {
                return ResourceManager.GetString("OobeTour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Getting ready.
        /// </summary>
        public static string OobeValidating {
            get {
                return ResourceManager.GetString("OobeValidating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to 4th &amp; Mayor.
        /// </summary>
        public static string OobeWelcomeTo4thAndMayor {
            get {
                return ResourceManager.GetString("OobeWelcomeTo4thAndMayor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Privacy Policy.
        /// </summary>
        public static string PrivacyPolicy {
            get {
                return ResourceManager.GetString("PrivacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LeftToRight.
        /// </summary>
        public static string ResourceFlowDirection {
            get {
                return ResourceManager.GetString("ResourceFlowDirection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to en-US.
        /// </summary>
        public static string ResourceLanguage {
            get {
                return ResourceManager.GetString("ResourceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Out.
        /// </summary>
        public static string SignOut {
            get {
                return ResourceManager.GetString("SignOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terms of Use.
        /// </summary>
        public static string TermsOfUse {
            get {
                return ResourceManager.GetString("TermsOfUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again.
        /// </summary>
        public static string TryAgain {
            get {
                return ResourceManager.GetString("TryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
